/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ichmed_trinketeers_util_KTXTexture */

#ifndef _Included_com_ichmed_trinketeers_util_KTXTexture
#define _Included_com_ichmed_trinketeers_util_KTXTexture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ichmed_trinketeers_util_KTXTexture
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ichmed_trinketeers_util_KTXTexture_load
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
