/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ichmed_trinketeers_util_texturesystem_ktxplugin_KTXTextureCodec */

#ifndef _Included_com_ichmed_trinketeers_util_texturesystem_ktxplugin_KTXTextureCodec
#define _Included_com_ichmed_trinketeers_util_texturesystem_ktxplugin_KTXTextureCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ichmed_trinketeers_util_texturesystem_ktxplugin_KTXTextureCodec
 * Method:    load
 * Signature: (Ljava/lang/String;)Lcom/ichmed/trinketeers/util/texturesystem/Texture;
 */
JNIEXPORT jobject JNICALL Java_com_ichmed_trinketeers_util_texturesystem_ktxplugin_KTXTextureCodec_load
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
