/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ichmed_trinketeers_savefile_DataLoader */

#ifndef _Included_com_ichmed_trinketeers_savefile_DataLoader
#define _Included_com_ichmed_trinketeers_savefile_DataLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ichmed_trinketeers_savefile_DataLoader
 * Method:    loadTextureFile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ichmed_trinketeers_savefile_DataLoader_loadTextureFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
